name = "portfolio"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

services = [
  { binding = "WORKER_SELF_REFERENCE", service = "portfolio" }
]

# Si decides crear un bucket R2, descomenta estas l√≠neas
# [r2_buckets]
# [[r2_buckets]]
# binding = "NEXT_INC_CACHE_R2_BUCKET"
# bucket_name = "portfolio-cache"